jira.base.url: https://xxxxxx.atlassian.net
jira.admin.username: xxxxxxx@gmail.com
jira.admin.api.token: xxxxxxxxxxxxxxxxxxxx
jira.minecraft.project.key: xx
jira.minecraft.project.parent: xxxx
debug.logging.enabled: false